name: Terraform destroy

on: 
  workflow_dispatch:
   inputs:
      Terraform-Apply:
         description: "Would you like to run 'terraform destroy' This will delete all infra and cannot be undone ?"
         required: true
         type: string
env:
   AWS_REGION: eu-west-1

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-24.04

    steps:

       - name: checkout
         uses: actions/checkout@v4

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
            role-to-assume: ${{ secrets.SECRETS_AWS_ASSUME }}
            aws-region: ${{ env.AWS_REGION }}

       - name: terraform Plan
         uses: dflook/terraform-destroy@v2
         with:
           path: infra
