name: Terraform Plan

on: 
  workflow_dispatch:
   inputs:
      Terraform-Apply:
         description: "Terraform Plan?"
         required: true
         type: string
env:
   AWS_REGION: eu-west-1
   


jobs:
  apply:
    runs-on: ubuntu-24.04

    steps:

       - name: checkout
         uses: actions/checkout@v4

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

       - name: terraform Plan
         uses: dflook/terraform-plan@v2
         with:
           path: Terraform      